<a href="https://colab.research.google.com/github/ypapay/CUK/blob/main/%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D_5%EC%A3%BC%EC%B0%A8_210930.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 파이썬 머신러닝 5주차
### 머신러닝 맛보기

### 2.4 Numpy 활용하기

In [1]:
#2.4.1 배열 만들기 및 초기화
import numpy as np
data = np.array([1, 2, 3, 4, 5, 6])
data_2d = np.array([[1,2,3], [4, 5, 6]])
data_random = np.random.randn(2, 3)
data_zeros = np.zeros(5)
data_ones = np.ones((2,3))
print(data)
print(data_2d)
print(data_2d.shape)
print(data_random)
print(data_zeros)
print(data_ones)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)
[[-0.04667963  0.42570666 -1.02452775]
 [-0.72874915  0.54011213  2.87086587]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [2]:
#2.4.2 배열 만들기(arrange 활용)
data_arange = np.arange(10, 121, 10)
data_reshape = data_arange.reshape((2, 6))
print(data_arange)
print(data_reshape)

[ 10  20  30  40  50  60  70  80  90 100 110 120]
[[ 10  20  30  40  50  60]
 [ 70  80  90 100 110 120]]


In [3]:
#2.4.3 배열의 요소 추출
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(data)
print(data[0][1])
print(data[0][1:])
data[0] = 100
print(data)
data[:] = 300
print(data)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[2 3]
[[100 100 100]
 [  4   5   6]
 [  7   8   9]]
[[300 300 300]
 [300 300 300]
 [300 300 300]]


In [4]:
#2.4.4 배열의 산술 연산
data = np.array([[5, 7, 9], [-7, -6, 19], [6, 8.9, 11]])
data_2 = data * 2
data_3 = data + 3
print(data)
print(data_2)
print(data_3)
print(data > data_2)


[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
[[ 10.   14.   18. ]
 [-14.  -12.   38. ]
 [ 12.   17.8  22. ]]
[[ 8.  10.  12. ]
 [-4.  -3.  22. ]
 [ 9.  11.9 14. ]]
[[False False False]
 [ True  True False]
 [False False False]]


In [6]:
#2.4.5 배열의 통계 메소드
data = np.array([[5, 7, 9], [-7, -6, 19], [6, 8.9, 11]])
print(data)
print(data.sum())
print(data.mean())
print(data.max())
print(data.min())
print(data.max(axis = 0))
index_1 = np.argmax(data, axis = 0)
print(index_1)

[[ 5.   7.   9. ]
 [-7.  -6.  19. ]
 [ 6.   8.9 11. ]]
52.9
5.877777777777777
19.0
-7.0
[ 6.   8.9 19. ]
[2 2 1]


In [7]:
#2.4.6 배열에 조건식 사용
data = np.random.randn(2, 3)
print(data)
print(data > 0)
total = (data < 0).sum()
print(total)
data_minus = np.where(data < 0, 0, data)
print(data_minus)

[[-0.13460265 -0.21728056 -1.813506  ]
 [-0.45231056  1.43120755 -0.69074945]]
[[False False False]
 [False  True False]]
5
[[0.         0.         0.        ]
 [0.         1.43120755 0.        ]]


In [8]:
#2.4.7 배열의 요소 정렬
data = np.array([[9, 7, 5], [19, -6, -9], [6, -2, 11]])
print(data)
data.sort(0)
print(data)
data.sort(1)
print(data)

[[ 9  7  5]
 [19 -6 -9]
 [ 6 -2 11]]
[[ 6 -6 -9]
 [ 9 -2  5]
 [19  7 11]]
[[-9 -6  6]
 [-2  5  9]
 [ 7 11 19]]


In [9]:
#2.4.8 배열의 브로드캐스팅
data_1 = np.array([[1, 2, 3], [4, 5, 6]])
data_2 = np.array([10, 11, 12])
sum = data_1 + data_2
multiply = data_1 + data_2
print(sum)
print(multiply)

[[11 13 15]
 [14 16 18]]
[[11 13 15]
 [14 16 18]]


### 3.4 Pandas 활용하기

In [10]:
#3.4.1 Series 객체 생성 및 인덱스 설정
import pandas as pd
obj = pd.Series([10, 20, 30, 40, 50])
obj_2 = pd.Series([10, 20, 30, 40, 50], index = ['a', 'b', 'c', 'd', 'e'])
print(obj)
print(obj.index)
print(obj[1])
print(obj_2)
print(obj_2[['a', 'e']])
print(obj_2[1:3])

0    10
1    20
2    30
3    40
4    50
dtype: int64
RangeIndex(start=0, stop=5, step=1)
20
a    10
b    20
c    30
d    40
e    50
dtype: int64
a    10
e    50
dtype: int64
b    20
c    30
dtype: int64


In [11]:
#3.4.2 Series 객체의 연산과 조건식
obj = pd.Series([10, 20, 30, 40])
print(obj * 10)
print('-' *30)
print(obj >= 20)

0    100
1    200
2    300
3    400
dtype: int64
------------------------------
0    False
1     True
2     True
3     True
dtype: bool


In [12]:
#3.4.3 Series 객체와 for문
data = pd.Series([35, 60, 85], index = ['유재석', '박명수', '태진아'])
print(data)
print('-' * 30)
for i, v in data.items() :
  print('%s : %d세'% (i, v))

유재석    35
박명수    60
태진아    85
dtype: int64
------------------------------
유재석 : 35세
박명수 : 60세
태진아 : 85세


In [13]:
#3.4.4 Series 객체와 딕셔너리
data = pd.Series({'유재석' : 35, '박명수' : 60, '태진아' : 85}, index = {'유재석', '박명수', '태진아', '정형돈', '하하'})
data['정형돈'] = 52
print(data)
print(data[3])

유재석    35.0
태진아    85.0
정형돈    52.0
하하      NaN
박명수    60.0
dtype: float64
nan


In [15]:
#3.4.5 DataFrame 객체 생성 및 인덱스 설정
data = {'이름' : ['유재석', '박명수', '정형돈', '하하'], 
        '나이' : [35, 60, 52, 38],
        '키' : [180, 175, 160, 150]}
frame = pd.DataFrame(data)
frame_2 = pd.DataFrame(data, columns = ['이름', '나이', '키', '몸무게'])
print(data)
print(frame)
print(frame_2)
print(frame.head(2))
print(frame.tail(2)) # 노트와 다름 확인 필요

{'이름': ['유재석', '박명수', '정형돈', '하하'], '나이': [35, 60, 52, 38], '키': [180, 175, 160, 150]}
    이름  나이    키
0  유재석  35  180
1  박명수  60  175
2  정형돈  52  160
3   하하  38  150
    이름  나이    키  몸무게
0  유재석  35  180  NaN
1  박명수  60  175  NaN
2  정형돈  52  160  NaN
3   하하  38  150  NaN
    이름  나이    키
0  유재석  35  180
1  박명수  60  175
    이름  나이    키
2  정형돈  52  160
3   하하  38  150


In [17]:
#3.4.6 DataFrame 요소 추출하기(loc과 iloc활용)
data = {'이름' : ['유재석', '박명수', '정형돈', '하하'],
        '나이' : [35, 60, 52, 38],
        '키' : [180, 175, 160, 150]}
frame = pd.DataFrame(data, index = ['첫째', '둘째', '셋째', '넷째'])
print(frame)
print(frame.loc['둘째', '이름'])
print(frame.loc['넷째', ['나이', '키']])
print('-' * 30)
print(frame.iloc[2, 0])
print(frame.iloc[3, :2])
print(frame.iloc[:, [0,2]])

     이름  나이    키
첫째  유재석  35  180
둘째  박명수  60  175
셋째  정형돈  52  160
넷째   하하  38  150
박명수
나이     38
키     150
Name: 넷째, dtype: object
------------------------------
정형돈
이름    하하
나이    38
Name: 넷째, dtype: object
     이름    키
첫째  유재석  180
둘째  박명수  175
셋째  정형돈  160
넷째   하하  150


In [18]:
#3.4.7 합계와 평균/정렬하기
data = {'이름' : ['유재석', '박명수', '정형돈', '하하'], 
        '나이' : [35, 60, 52, 38],
        '키' : [180, 175, 160, 150]}
frame = pd.DataFrame(data)
frame_2 = frame.iloc[:, [1,2]]
rank = frame.sort_values(by = ['나이'], ascending = False)
total = frame_2.sum(axis = 0)
avg = frame_2.mean(axis = 0)

print(frame_2)
print(rank)
print(total)
print(avg)

   나이    키
0  35  180
1  60  175
2  52  160
3  38  150
    이름  나이    키
1  박명수  60  175
2  정형돈  52  160
3   하하  38  150
0  유재석  35  180
나이    185
키     665
dtype: int64
나이     46.25
키     166.25
dtype: float64
